affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
env:
  api:
    domainsAPIEnabled: true
    pnpAPIEnabled: true
  blockchain:
    blockchainApiKeyExistingSecret: odis-signer1-forno-key
    blockchainProvider: https://alfajores-forno.celo-testnet.org
  db:
    cloudSqlProxy: false
    database: phoneNumberPrivacy
    host: odis-signer1-alfajores-db-postgresql-hl
    passwordExistingSecret: odis-signer1-db-password
    port: 5432
    type: postgres
    useSsl: false
    username: cLabs
  keystore:
    domainsKeyLatestVersion: null
    domainsKeyNameBase: odis-signer1-alfajores-domains
    gcp:
      projectID: celo-testnet-production
    pnpKeyLatestVersion: null
    pnpKeyNameBase: odis-signer1-alfajores-phoneNumberPrivacy
    type: GoogleSecretManager
  log:
    format: stackdriver
    level: trace
  odis:
    mockDek: 0x034846bc781cacdafc66f3a77aa9fc3c56a9dadcd683c72be3c446fee8da041070
    odisSignerTimeout: "6000"
    shouldMockAccountService: "false"
    shouldMockRequestService: "false"
    testQuotaBypassPercentage: "50"
  tracing:
    enabled: true
    endpoint: "http://grafana-agent.monitoring:14268/api/traces"
    serviceName: "odis-signer1-alfajores-k8s"
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: us-west1-docker.pkg.dev/devopsre/social-connect/odis-signer
  tag: "odis-signer-3.1.1"
imagePullSecrets: []
ingress:
  annotations: {}
  className: nginx
  enabled: false
  hosts: []
  tls: []
livenessProbe: {}
nameOverride: ""
nodeSelector: {}
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "3000"
  prometheus.io/scrape: "true"
podSecurityContext: {}
readinessProbe: {}
replicaCount: 1
resources: {}
securityContext: {}
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: odis-signer1-alfajores@celo-testnet-production.iam.gserviceaccount.com
  create: true
  name: ""
tolerations: []
